[package]
name = "tcp-rusted"
version = "0.1.0"
authors = ["MadoScientist97"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"
